SET SERVEROUTPUT ON;

CREATE SEQUENCE SEC_PERSONA
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE TABLE PERSONA(ID_PERSONA INTEGER, NOMBRE VARCHAR2(20), EDAD INTEGER, CONSTRAINT PK_ID_PERSONA PRIMARY KEY (ID_PERSONA));

CREATE OR REPLACE PROCEDURE GUARDAR_PERSONA(MY_ID OUT INTEGER, MY_NOMBRE IN VARCHAR2, MY_EDAD IN INTEGER)
AS
BEGIN
SELECT SEC_PERSONA.NEXTVAL INTO MY_ID FROM DUAL;
INSERT INTO PERSONA VALUES(MY_ID, MY_NOMBRE, MY_EDAD);
END;
/

DECLARE

VALOR INTEGER;
BEGIN
GUARDAR_PERSONA(VALOR, 'JUAN', 23);
END;
/
SELECT *FROM PERSONA;
